app/routes/auth.py
from flask import Blueprint, render_template

from app.decorators import check_for_jwt


auth_render = Blueprint('auth_render', __name__, url_prefix='/auth')

@auth_render.get('/login')
def render_login():
	'''
	Rota de login.
	'''
	return render_template('login.html', title='Login')

@auth_render.get('/cadastro')
def render_cadastro():
	'''
	Rota de cadastro.
	'''
	return render_template('cadastro.html', title='Cadastro')

@auth_render.get('/minha-conta')
@check_for_jwt
def render_minha_conta():
	'''
	Rota "minha-conta".

	Serve como o perfil do usuário, e também
	página que o usário pode atualizar a senha e o nome.
	'''
	return render_template('minha_conta.html', title='Minha Conta')

app/routes/home.py
from flask import Blueprint, render_template

from app.utils import response
from app.utils.enums import Moedas, Instituicoes, TipoTransacao


home_render = Blueprint('home_render', __name__)

@home_render.get('/')
def home_route():
	'''
	Rota padrão (home) da aplicação.
	'''
	return render_template('home.html', title='Home')


@home_render.get('/enum/<string:classe>')
def rota_informacoes_enum(classe: str):
	'''
	Retorna classes enumeradores existentes.

	Args:
		classe: str - classe `Enum` a ser exibida.
	
	Returns:
		CÓD. 404 (NOT_FOUND): Classe não encontrada;
		CÓD. 200 (OK): Sucesso - retorna a classe em formato json.
	'''
	enums = {
		'moedas': Moedas.to_json(),
		'tipo-transacao': TipoTransacao.to_json(),
		'instituicao-bancaria': Instituicoes.to_json(),
	}

	if classe in enums.keys():
		return response(200, enums[classe])

	return response(404, 'Nenhuma classe encontrada com o nome informado.')

app/routes/main.py
from flask import Blueprint, render_template

from app.decorators import check_for_jwt


main_render = Blueprint('main_render', __name__, url_prefix='/app')

@main_render.get('/')
@check_for_jwt
def render_dashboard():
	'''
	Rota dashboard (painel de controle).

	É a página principal da aplicação, o "rosto" do aplicativo.
	'''
	return render_template('dashboard.html', title='Dashboard')

@main_render.get('/historico')
@check_for_jwt
def render_historico():
	'''
	Rota histórico.

	Reúne uma listagem dos dados do usuário, como 
	contas bancárias, transações e transferências bancárias
	em tabelas.
	'''
	return render_template('historico.html', title='Histórico')

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- Bootstrap: CSS only -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

	<link rel="stylesheet" href="../static/css/style.css">

	<title>{{ title }} - Smart Money</title>
</head>

<body class="bg-white">
	<nav class="navbar navbar-expand-lg navbar bg-light shadow">
		<div class="container">
			<a class="navbar-brand px-2" href="#">
				<img style="height: 54px;" src="../static/img/logo.png" alt="logo">
			</a>

			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent"
				aria-controls="navbarContent" aria-expanded="false" aria-label="Navegar">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse ps-4" id="navbarContent">
				<div class="navbar-nav">
					<a class="nav-link" href="{{ url_for('main_render.render_dashboard') }}">MEU APP</a>
					<a class="nav-link" href="{{ url_for('home_render.home_route') }}">HOME</a>
					<a class="nav-link" href="{{ url_for('auth_render.render_login') }}">LOGIN</a>
					<a class="nav-link" href="{{ url_for('auth_render.render_cadastro') }}">CADASTRO</a>
				</div>
			</div>
		</div>
	</nav>

	{% block conteudo %}
	{% endblock %}
</body>

<!-- JQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
	crossorigin="anonymous"></script>

<!-- Bootstrap: JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>

<script src="../static/js/user/user.js"></script>
<script src="../static/js/utils.js"></script>

{% block script %}{% endblock %}

</html>

templates/cadastro.html
{% extends 'base.html' %}

{% block conteudo %}

<div class="container">
	<main class="row align-items-center">
		<div class="col">
			<div class="py-5 text-center">
				<h2 class="h2">CADASTRO</h2>
			</div>
			
			<div>
				<form class="row justify-content-center px-5 mb-5">
					<div class="col-md-8">
						<div class="input-group has-validation mb-3">
							<div class="form-floating">
								<input type="email" class="form-control" id="email-cadastro" placeholder="Email">
								<label for="email-cadastro">Email</label>
							</div>
							<div class="invalid-feedback" id="email-cadastro-erro"></div>
						</div>
			
						<div class="input-group has-validation mb-3">
							<div class="form-floating">
								<input type="text" class="form-control" id="nome-cadastro" placeholder="Email">
								<label for="nome-cadastro">Nome de usuário</label>
							</div>
							<div class="invalid-feedback" id="nome-cadastro-erro"></div>
						</div>
						
						<div class="show-password-group">
							<div class="input-group has-validation mb-2">
								<div class="form-floating">
									<input type="password" class="form-control toggle-visibility" id="senha-cadastro" placeholder="Senha">
									<label for="senha">Senha</label>
								</div>
								<div class="invalid-feedback" id="senha-cadastro-erro"></div>
							</div>
							<div class="d-flex justify-content-end">
								<div class="form-check mb-3">
									<label class="form-check-label" for="mostrar-senha">
										Mostrar senha
									</label>
									<input class="form-check-input toggle-visibility-button" type="checkbox" value="" id="mostrar-senha">
								</div>
							</div>
						</div>
					</div>
				</form>

				<div class="row justify-content-center text-center">
					<div class="col-auto">
						<button id="cadastro-submit" class="px-5 btn btn-indigo btn-lg btn-primary rounded-pill" type="submit">CADASTRAR</button>
					</div>

					<p class="h6 my-4">Já possui uma conta? 
						<a class="btn btn-light rounded-pill mx-2" href="{{ url_for('auth_render.render_login') }}">ENTRAR</a> 
					</p>
				</div>
			</div>
		</div>
	</main>
</div>

{% endblock %}

{% block script %}
<script src="../static/js/show_password.js"></script>
{% endblock %}

templates/dashboard.html
{% extends 'app_base.html' %}

{% block conteudo %}

<div class="container-fluid px-5 mt-5">
	<header>
		<h1 class="display-4">Bem vindo</h1>
		<hr>
	</header>

	<section>
		<div class="row g-4 py-3">
			<article class="col">
				<div class="card rounded-4 shadow">
					<div class="d-flex flex-column px-5 py-5 pb-3">
						<header class="d-flex align-items-center pb-2">
							<svg fill="#dc3545" class="me-3" height="2em" width="2em">
								<use xlink:href="#arrow-down" />
							</svg>
							<h3 class="mb-0 fw-bold">DESPESAS</h3>
						</header>

						<h3 class="d-flex">
							<p id="valor-despesas"></p>
						</h3>

						<table class="table" id="tabela-despesas">
							<thead>
								<tr>
									<th scope="col"></th>
									<th scope="col">Valor</th>
									<th scope="col">Categoria</th>
									<th scope="col">Conta bancária</th>
								</tr>
							</thead>
							<tbody>
								<tr id="despesas-default-row">
									<th scope='row'>...</th>
									<td>...</td>
									<td>...</td>
									<td>...</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</article>

			<article class="col">
				<div class="card rounded-4 shadow">
					<div class="d-flex flex-column px-5 py-5 pb-3">
						<header class="d-flex align-items-center pb-2">
							<svg class="me-3" height="2em" width="2em">
								<use xlink:href="#circle-arrows" />
							</svg>
							<h3 class="mb-0 fw-bold">TRANSFERÊNCIAS</h3>
						</header>

						<h3 class="d-flex">
							<p id="valor-transferencias"></p>
						</h3>

						<table class="table" id="tabela-transferencias">
							<thead>
								<tr>
									<th scope="col"></th>
									<th scope="col">Valor</th>
									<th scope="col">Conta origem</th>
									<th scope="col">Conta destino</th>
								</tr>
							</thead>
							<tbody>
								<tr id="transferencias-default-row">
									<th scope='row'>...</th>
									<td>...</td>
									<td>...</td>
									<td>...</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</article>

			<article class="col">
				<div class="card rounded-4 shadow">
					<div class="d-flex flex-column px-5 py-5 pb-3">
						<header class="d-flex align-items-center pb-2">
							<svg fill="#198754" class="me-3" height="2em" width="2em">
								<use xlink:href="#arrow-up" />
							</svg>
							<h3 class="mb-0 fw-bold">RECEITAS</h3>
						</header>

						<h3 class="d-flex">
							<p id="valor-receitas"></p>
						</h3>
						
						<table class="table" id="tabela-receitas">
							<thead>
								<tr>
									<th scope="col"></th>
									<th scope="col">Valor</th>
									<th scope="col">Categoria</th>
									<th scope="col">Conta bancária</th>
								</tr>
							</thead>
							<tbody>
								<tr id="receitas-default-row">
									<th scope='row'>...</th>
									<td>...</td>
									<td>...</td>
									<td>...</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</article>
		</div>
	</section>

	<section>
		<header class="d-flex align-items-center">
			<h4 class="display-6 me-2">Contas bancárias</h4>
			<a class="btn btn-light rounded-pill mx-2" data-bs-toggle="modal" data-bs-target="#formContaBancaria"
				href="#">ADICIONAR</a>
		</header>

		<hr>

		<div class="row g-4 py-3" id="contas-bancarias-resume">

			<div id="msg-sem-contas-bancarias" class="text-center py-5">
				<h2>
					Adicione sua primeira conta bancária </br>

					<a class="my-4 btn btn-lg btn-indigo rounded-pill text-white mx-2" data-bs-toggle="modal" data-bs-target="#formContaBancaria"
						href="#">ADICIONAR</a>
				</h2>
			</div>

			<!-- Populate on JS -->
		</div>
	</section>
</div>

{% endblock %}

{% block script %}

<script src="../static/js/dashboard/popular_dashboard.js"></script>
<script src="../static/js/dashboard/dashboard.js"></script>

{% endblock %}

templates/historico.html
{% extends 'app_base.html' %}

{% block conteudo %}

<div class="container-fluid px-4 mt-5">
	<!-- DESPESAS -->
	<article class="col p-3 my-5 bg-white border shadow rounded-4">
		<div class="p-2">
			<div class="ms-5">
				<header class="d-flex align-items-center pb-2">
					<svg fill="#dc3545" class="me-3" height="2em" width="2em">
						<use xlink:href="#arrow-down" />
					</svg>
					<h3 class="mb-0 fw-bold">DESPESAS</h3>
				</header>
				<h3>
					<p id="valor-despesas"></p>
				</h3>
			</div>

			<section class="row p-3 mb-2">
				<div class="col text-center">
					<h5>
						PAGAS <br>
						<small class="text-muted" id="despesas-pagas"></small>
					</h5>
				</div>

				<div class="col text-center">
					<h5>
						NÃO PAGAS <br>
						<small class="text-muted" id="despesas-nao-pagas"></small>
					</h5>
				</div>
			</section>

			<table class="table" id="tabela-despesas">
				<thead>
					<tr>
						<th scope="col">Resolvido</th>
						<th scope="col">Valor</th>
						<th scope="col">Categoria</th>
						<th scope="col">Conta</th>
						<th scope="col">Descrição</th>
						<th scope="col">Ações</th>
					</tr>
				</thead>
				<tbody>
					<tr id="despesas-default-row">
						<th scope="row">...</th>
						<td>...</td>
						<td>...</td>
						<td>...</td>
						<td>...</td>
						<td>...</td>
					</tr>
				</tbody>
			</table>
		</div>
	</article>

	<!-- RECEITAS -->
	<article class="col p-3 my-5 bg-white border shadow rounded-4">
		<div class="p-2">
			<div class="ms-5">
				<header class="d-flex align-items-center pb-2">
					<svg fill="#198754" class="me-3" height="2em" width="2em">
						<use xlink:href="#arrow-up" />
					</svg>
					<h3 class="mb-0 fw-bold">RECEITAS</h3>
				</header>
				<h3>
					<p id="valor-receitas"></p>
				</h3>
			</div>

			<section class="row p-3 mb-2">
				<div class="col text-center">
					<h5>
						RECEBIDAS <br>
						<small class="text-muted" id="receitas-recebidas"></small>
					</h5>
				</div>

				<div class="col text-center">
					<h5>
						NÃO RECEBIDAS <br>
						<small class="text-muted" id="receitas-nao-recebidas"></small>
					</h5>
				</div>
			</section>

			<table class="table" id="tabela-receitas">
				<thead>
					<tr>
						<th scope="col">Resolvido</th>
						<th scope="col">Valor</th>
						<th scope="col">Categoria</th>
						<th scope="col">Conta</th>
						<th scope="col">Descrição</th>
						<th scope="col">Ações</th>
					</tr>
				</thead>
				<tbody>
					<tr id="receitas-default-row">
						<th scope="row">...</th>
						<td>...</td>
						<td>...</td>
						<td>...</td>
						<td>...</td>
						<td>...</td>
					</tr>
				</tbody>
			</table>
		</div>
	</article>

	<div class="row mb-3">
		<!-- CONTAS BANCÁRIAS -->
		<article class="col p-3 mx-3 my-2 bg-white border shadow rounded-4">
			<div class="p-2">
				<div class="ms-5">
					<header class="d-flex align-items-center pb-2">
						<svg class="me-3" height="2em" width="2em">
							<use xlink:href="#bank" />
						</svg>
						<h3 class="mb-0 fw-bold">CONTAS BANCÁRIAS</h3>
					</header>
					<h3>
						<p id="saldo-contas-bancarias"></p>
					</h3>
				</div>
				<table class="table" id="tabela-contas-bancarias">
					<thead>
						<tr>
							<th scope="col">Nome</th>
							<th scope="col">Saldo</th>
							<th scope="col">Instituição bancária</th>
							<th scope="col">Ações</th>
						</tr>
					</thead>
					<tbody>
						<tr id="contas-bancarias-default-row">
							<th scope="row">...</th>
							<td>...</td>
							<td>...</td>
							<td>...</td>
						</tr>
					</tbody>
				</table>
			</div>
		</article>
		
		<!-- TRANSFERÊNCIAS -->
		<article class="col p-3 mx-3 my-2 bg-white border shadow rounded-4">
			<div class="p-2">
				<div class="ms-5">
					<header class="d-flex align-items-center pb-2">
						<svg class="me-3" height="2em" width="2em">
							<use xlink:href="#circle-arrows" />
						</svg>
						<h3 class="mb-0 fw-bold">TRANSFERÊNCIAS</h3>
					</header>
					<h3>
						<p id="valor-transferencias"></p>
					</h3>
				</div>
				<table class="table" id="tabela-transferencias">
					<thead>
						<tr>
							<th scope="col">Valor</th>
							<th scope="col">Conta origem</th>
							<th scope="col">Conta destino</th>
							<th scope="col">Ações</th>
						</tr>
					</thead>
					<tbody>
						<tr id="transferencias-default-row">
							<th scope="row">...</th>
							<td>...</td>
							<td>...</td>
							<td>...</td>
						</tr>
					</tbody>
				</table>
			</div>
		</article>
	</div>
</div>

{% endblock %}

{% block script %}

<script src="../static/js/historico/popular_historico.js"></script>
<script src="../static/js/historico/forms.js"></script>

{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block conteudo %}

<main class="container-fluid">
	<div class="row align-items-center" style="height: 80vh;">
		<div class="col h-25 bg-light shadow-lg rounded-pill rounded-start"></div>

		<div class="col-4 h-25 text-center">
			<div class="row h-100 align-items-center">
				<h1 class="fs-1">SEJA BEM VINDO</h1>
			</div>
		</div>

		<div class="col h-25 bg-light shadow-lg rounded-pill rounded-end"></div>
	</div>
</main>


{% endblock %}

{% block script %}
<script src="../static/js/show_password.js"></script>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block conteudo %}

<div class="container">
	<main class="row align-items-center">
		<div class="col">
			<div class="py-5 text-center">
				<h2 class="h2">LOGIN</h2>
			</div>
			
			<form class="row justify-content-center px-5 mb-5">
				<div class="col-md-8">
					<div class="input-group has-validation mb-3">
						<div class="form-floating">
							<input type="email" class="form-control" id="email-login" placeholder="Email">
							<label for="email-login">Email</label>
						</div>
						<div class="invalid-feedback" id="email-login-erro"></div>
					</div>

					<div class="show-password-group">
						<div class="input-group has-validation mb-2">
							<div class="form-floating">
								<input type="password" class="form-control toggle-visibility" id="senha-login" placeholder="Senha">
								<label for="senha">Senha</label>
							</div>
							<div class="invalid-feedback" id="senha-login-erro"></div>
						</div>
						
						<div class="d-flex justify-content-end">
							<div class="form-check mb-3">
								<label class="form-check-label" for="mostrar-senha">
									Mostrar senha
								</label>
								<input class="form-check-input toggle-visibility-button" type="checkbox" value="" id="mostrar-senha">
							</div>
						</div>
					</div>
				</div>
			</form>

			<div class="row justify-content-center text-center">
				<div class="col-auto">
					<button id="login-submit" class="px-5 btn btn-indigo btn-lg btn-primary rounded-pill" type="submit">ENTRAR</button>
				</div>

				<p class="h6 my-4">Ainda não possui uma conta? 
					<a class="btn btn-light rounded-pill mx-2" href="{{ url_for('auth_render.render_cadastro') }}">CADASTRAR</a> 
				</p>
			</div>
		</div>
	</main>
</div>

{% endblock %}

{% block script %}
<script src="../static/js/show_password.js"></script>
{% endblock %}

templates/minha_conta.html
{% extends 'app_base.html' %}

{% block conteudo %}

<div class="container mt-5">
	<header>
		<h1 class="display-4">Minha conta</h1>
		<hr>
	</header>

	<div class="row justify-content-center">
		<div class="text-center mt-2 mb-4">
			<span class="fs-2 fw-light" id="email-atualizar"></span>
		</div>

		<form class="mb-2 w-75">
			<div class="row mb-3 gy-3">
				<div class="col">
					<div class="input-group has-validation">
						<div class="form-floating">
							<input type="text" class="form-control" id="nome-atualizar" placeholder="Nome">
							<label for="nome-atualizar">Nome de usuário</label>
						</div>
						<div class="invalid-feedback" id="nome-atualizar-erro"></div>
					</div>
				</div>
				<div class="col">
					<div class="form-floating">
						<select id="moedas-atualizar" class="form-select">
							</select>
						<label for="moedas-atualizar">Moedas disponíveis</label>
					</div>
				</div>
			</div>
			
			<div class="show-password-group">
				<div class="input-group has-validation mb-2">
					<div class="form-floating">
						<input type="password" class="form-control toggle-visibility" id="senha-atual-atualizar" placeholder="Senha">
						<label for="senha-atual-atualizar">Senha atual</label>
					</div>
					<div class="invalid-feedback" id="senha-atual-atualizar-erro"></div>
				</div>
				
				<div class="d-flex justify-content-end">
					<div class="form-check mb-3">
						<label class="form-check-label" for="mostrar-senha-atual">
							Mostrar senha atual
						</label>
						<input class="form-check-input toggle-visibility-button" type="checkbox" value="" id="mostrar-senha-atual">
					</div>
				</div>
			</div>

			<div class="show-password-group">
				<div class="input-group has-validation mb-2">
					<div class="form-floating">
						<input type="password" class="form-control toggle-visibility" id="senha-nova-atualizar" placeholder="Senha">
						<label for="senha">Nova senha</label>
					</div>
					<div class="invalid-feedback" id="senha-nova-atualizar-erro"></div>
				</div>
				
				<div class="d-flex justify-content-end">
					<div class="form-check mb-3">
						<label class="form-check-label" for="mostrar-nova-senha">
							Mostrar nova senha
						</label>
						<input class="form-check-input toggle-visibility-button" type="checkbox" value="" id="mostrar-nova-senha">
					</div>
				</div>
			</div>
		</form>
		<div class="text-center">
			<button type="submit" id="atualizar-submit"
				class="px-5 btn btn-indigo btn-lg btn-primary rounded-pill">
				ATUALIZAR
			</button>
		</div>
	</div>
</div>

{% endblock %}

{% block script %}

<script src="../static/js/user/atualizar_conta.js"></script>
<script src="../static/js/show_password.js"></script>

{% endblock %}